# Generated by Django 5.0.4 on 2024-06-29 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='departamento',
            new_name='departamentos',
        ),
    ]
