# Generated by Django 5.0.4 on 2024-06-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas_extras', '0004_registrohoraextra_horas_utilizadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrohoraextra',
            old_name='horas_utilizadas',
            new_name='hora_utilizada',
        ),
    ]
