# Generated by Django 5.0.4 on 2024-05-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='name',
            new_name='nome',
        ),
    ]
